const surprisePrompts = [
  "What is the capital of France?",
  "Define a binary tree.",
  "What is 2 + 2?",
  "Explain recursion in one sentence.",
  "What does HTML stand for?",
  "Name a programming language.",
  "What is the color of the sky?",
  "How many continents are there?",
  "What is the square root of 16?",
  "Who wrote 'Romeo and Juliet'?",
  "Define a variable in programming.",
  "What is an algorithm?",
  "Name one planet in the solar system.",
  "What is the smallest prime number?",
  "What is the speed of light?",
  "Who painted the Mona Lisa?",
  "What is 5 factorial?",
  "What is the chemical symbol for water?",
  "Define an array in programming.",
  "What is 7 multiplied by 8?",
  "What does CSS stand for?",
  "Name a primary color.",
  "What is the boiling point of water?",
  "Who discovered gravity?",
  "What does JSON stand for?",
  "What is the Pythagorean theorem?",
  "Name a mammal.",
  "What is an IP address?",
  "What is the square of 9?",
  "Define a function in programming.",
  "What is the symbol for pi?",
  "Name one type of data structure.",
  "What does HTTP stand for?",
  "Name a famous scientist.",
  "What is a loop in programming?",
  "What is 10 divided by 2?",
  "Name a shape with three sides.",
  "What is the largest ocean?",
  "Define a string in programming.",
  "What does RAM stand for?",
  "Name a non-renewable energy source.",
  "What is 12 + 13?",
  "What does DNS stand for?",
  "Name a type of cloud.",
  "What is the freezing point of water?",
  "What does API stand for?",
  "Name a type of triangle.",
  "What is the capital of Japan?",
  "What is an HTTP request?",
  "Define an object in JavaScript."
];

export default surprisePrompts;
