const surprisePrompts = [
  "What is the meaning of life?",
  "Tell me a fun fact about space!",
  "If I could time travel, where should I go and why?",
  "How do black holes work?",
  "What’s the secret to happiness?",
  "Why do we dream?",
  "Can AI have emotions?",
  "What’s the most amazing invention in human history?",
  "Explain quantum mechanics in simple terms.",
  "What’s the best way to learn a new skill?",
  "How does the internet actually work?",
  "What’s the most interesting animal on Earth?",
  "If you could recommend one book, what would it be?",
  "Why do cats purr?",
  "What’s the best way to cook a perfect pasta dish?",
  "What’s the story behind the pyramids?",
  "What are some cool facts about the ocean?",
  "Can you explain string theory like I’m five?",
  "What’s the secret to a good night’s sleep?",
  "How do planes stay in the air?",
  "Why do humans love music?",
  "What’s the most mind-blowing fact about the universe?",
  "How do bees make honey?",
  "What’s the future of AI?",
  "Why do we celebrate birthdays?",
  "What’s the science behind rainbows?",
  "What’s the most exciting historical event you know?",
  "How do video games actually work?",
  "What’s your favorite joke?",
  "What’s the most underrated travel destination?",
  "What’s the difference between a star and a planet?",
  "If money didn’t exist, how would society work?",
  "Why do leaves change color in autumn?",
  "What’s the best way to start your morning?",
  "What’s the history behind the invention of the wheel?",
  "What’s the weirdest food in the world?",
  "Why does time feel faster as we grow older?",
  "If I could have one superpower, what should it be?",
  "What’s the most mind-boggling paradox in science?",
];

export default surprisePrompts;
